TERMUX_PKG_HOMEPAGE=https://freedesktop.org/software/pulseaudio/pavucontrol/
TERMUX_PKG_DESCRIPTION="PulseAudio Volume Control"
TERMUX_PKG_LICENSE="GPL-2.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=6.0
TERMUX_PKG_SRCURL=https://gitlab.freedesktop.org/pulseaudio/pavucontrol/-/archive/v$TERMUX_PKG_VERSION/pavucontrol-v$TERMUX_PKG_VERSION.tar.gz
TERMUX_PKG_SHA256=bf94e8b24bd11f48567908d0bf2d8a80d4af30f637694e753e3d3d6447a53678
TERMUX_PKG_DEPENDS="glib, glib-bin, gtk4, gtkmm4, json-glib, libcanberra, libsigc++-3.0, pulseaudio"
TERMUX_PKG_AUTO_UPDATE=true
